server {
	listen 80;
	server_name theapplewiki.com;

	include /srv/wiki/nginx/mw.conf;

	location /discord {
		return 302 https://discord.gg/zk2HggAw89;
	}

	location = /robots.txt {
		rewrite ^ /resources/applewiki/robots.txt;
	}

	location = /favicon.ico {
		rewrite ^ /resources/applewiki/favicon.png;
	}

	location ~ ^/apple-touch-icon(-precomposed)?.png {
		rewrite ^ /resources/applewiki/apple-touch-icon.png;
	}
}
