---
services:
  mediawiki:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '127.0.0.1:9000:9000'
    links:
      - database
      - redis
    volumes:
      - './LocalSettings.php:/var/www/html/LocalSettings.php'
      - './html/composer.local.json:/var/www/html/composer.local.json'
      - './html/composer.lock:/var/www/html/composer.lock'
      - './html/skins/Citizen:/var/www/html/skins/Citizen'
      - './html/extensions:/var/www/html/extensions'
      - './html/images:/var/www/html/images'
      - './html/vendor:/var/www/html/vendor'
      - './html/sitemap:/var/www/html/sitemap'
      - './cache:/var/www/html/cache'
      - './php.ini:/usr/local/etc/php/conf.d/zz-wiki.ini'
      - './php-fpm.conf:/usr/local/etc/php-fpm.d/zz-wiki.conf'
    environment:
      WG_DB_PASSWORD: '${MYSQL_PASSWORD}'
      WG_SECRET_KEY: '${WG_SECRET_KEY}'
      WG_AUTHENTICATION_TOKEN_VERSION: '${WG_AUTHENTICATION_TOKEN_VERSION}'
      WG_SENDGRID_API_KEY: '${WG_SENDGRID_API_KEY}'
      WG_HCAPTCHA_SITE_KEY: '${WG_HCAPTCHA_SITE_KEY}'
      WG_HCAPTCHA_SECRET_KEY: '${WG_HCAPTCHA_SECRET_KEY}'
      WG_DISCORD_WEBHOOK_APPLEWIKI: '${WG_DISCORD_WEBHOOK_APPLEWIKI}'
      WG_DISCORD_WEBHOOK_HACKDIFFERENT: '${WG_DISCORD_WEBHOOK_HACKDIFFERENT}'
      WG_CLOUDFLARE_ZONE: '${WG_CLOUDFLARE_ZONE}'
      WG_CLOUDFLARE_TOKEN: '${WG_CLOUDFLARE_TOKEN}'

  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    volumes:
      - './db:/var/lib/mysql'

  redis:
    image: redis
    restart: always
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - './redis/data:/data'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    restart: always
    volumes:
      - './elasticsearch/data:/usr/share/elasticsearch/data'
    environment:
      - discovery.type=single-node
